create table public.client_intake (
  id uuid not null default gen_random_uuid (),
  company_id uuid not null,
  status text null default 'draft'::text,
  submitted_at timestamp with time zone null,
  validated_at timestamp with time zone null,
  validated_by_agent boolean null default false,
  validation_report jsonb null,
  legal_name text null,
  dba_name text null,
  uei text null,
  cage_code text null,
  duns text null,
  ein text null,
  business_structure text null,
  years_in_business integer null,
  employee_count integer null,
  annual_revenue numeric null,
  primary_naics text null,
  secondary_naics text[] null default '{}'::text[],
  set_aside_certifications jsonb null default '[]'::jsonb,
  cmmc_level text null,
  cmmc_cert_number text null,
  cmmc_expiration date null,
  cmmc_cert_url text null,
  fedramp_level text null,
  security_certifications jsonb null default '[]'::jsonb,
  cloud_platforms jsonb null default '[]'::jsonb,
  iac_tools text[] null default '{}'::text[],
  container_tools text[] null default '{}'::text[],
  cicd_tools text[] null default '{}'::text[],
  security_tools jsonb null default '{"siem": [], "cmmc_controls": [], "vulnerability_scanners": []}'::jsonb,
  methodologies text[] null default '{}'::text[],
  proprietary_tools jsonb null default '[]'::jsonb,
  escalation_rate numeric null,
  overhead_rate numeric null,
  ga_rate numeric null,
  fee_margin numeric null,
  fringe_rate numeric null,
  travel_budget numeric null,
  license_costs numeric null,
  hardware_costs numeric null,
  cloud_costs numeric null,
  primary_office jsonb null,
  additional_locations jsonb null default '[]'::jsonb,
  facility_clearance text null,
  existing_infrastructure text null,
  subcontractors jsonb null default '[]'::jsonb,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null,
  constraint client_intake_pkey primary key (id),
  constraint client_intake_company_id_fkey foreign KEY (company_id) references companies (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_client_intake_company_id on public.client_intake using btree (company_id) TABLESPACE pg_default;

create trigger update_client_intake_updated_at BEFORE
update on client_intake for EACH row
execute FUNCTION update_updated_at_column ();